dev

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,67 +8,105 @@ permissions:
   contents: write
 
 jobs:
-  build:
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ windows-latest ]
-        #        os: [ windows-latest, macos-latest ]
-        include:
-          - os: windows-latest
-            os-caption: windows
-    #          - os: macos-latest
-    #            os-caption: macos
+  #  build:
+  #    strategy:
+  #      fail-fast: false
+  #      matrix:
+  #        os: [ windows-latest ]
+  #        #        os: [ windows-latest, macos-latest ]
+  #        include:
+  #          - os: windows-latest
+  #            os-caption: windows
+  #    #          - os: macos-latest
+  #    #            os-caption: macos
+  #
+  #    runs-on: ${{matrix.os}}
+  #
+  #    env:
+  #      QT_VERSION: dev
+  #
+  #    steps:
+  #      - uses: seanmiddleditch/gha-setup-ninja@v5
+  #
+  #      - name: Set up Python
+  #        uses: actions/setup-python@v4
+  #        with:
+  #          python-version: '3.x'  # 指定 Python 版本
+  #
+  #      - name: Install Python dependencies
+  #        run: |
+  #          pip install html5lib flex bison gperf
+  #
+  #      - name: Install LLVM and Clang
+  #        run: |
+  #          choco install llvm
+  #
+  #      - name: Clone Qt repo
+  #        run: |
+  #          git clone --recursive https://code.qt.io/qt/qt5.git qt -b '${{env.QT_VERSION}}'
+  #          cd qt
+  #          perl init-repository.pl -f --module-subset=all,-qtopcua
+  #
+  #      - name: Set up MSVC
+  #        uses: ilammy/msvc-dev-cmd@v1
+  #        if: contains(matrix.os, 'windows')
+  #
+  #      - name: Build Qt (Windows)
+  #        if: contains(matrix.os, 'windows')
+  #        env:
+  #          CL: /MP # Build with multiple processes
+  #        run: |
+  #          mkdir qt_build
+  #          cd qt_build
+  #          ..\qt\configure.bat -prefix "..\qt_static" -release -static -static-runtime -optimize-size -opensource -make examples  -no-pch -install-examples-sources -examplesdir "..\qt_static\examples" -no-dbus -no-openssl -no-feature-accessibility -- -DBUILD_qtwebengine=OFF
+  #          cmake --build . --parallel 4
+  #          cmake --install .
+  #
+  #      - name: Build Qt (macOS)
+  #        if: contains(matrix.os, 'macos')
+  #        run: |
+  #          mkdir qt_build
+  #          cd qt_build
+  #          ../qt/configure -static -static-runtime -release -optimize-size -prefix "../qt_static" -no-feature-accessibility -- -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
+  #          cmake --build . --parallel 3
+  #          cmake --install .
+  #
+  #      - name: Package binaries
+  #        run: |
+  #          # 安装 zstd 和 tar
+  #          choco install zstd
+  #          choco install gnuwin32-tar
+  #
+  #          # 使用 tar 打包并压缩为 .tar.zst
+  #          tar -cf - qt_static | zstd -o qt-${{env.QT_VERSION}}-static-${{matrix.os-caption}}.tar.zst
+  #
+  #      - uses: actions/upload-artifact@v4
+  #        with:
+  #          name: qt-static-${{matrix.os-caption}}
+  #          path: qt-*.tar.zst
 
-    runs-on: ${{matrix.os}}
-
-    env:
-      QT_VERSION: dev
-
+  release:
+    runs-on: ubuntu-latest
+    needs: build
     steps:
-      - uses: seanmiddleditch/gha-setup-ninja@v5
-
-      - name: Clone Qt repo
-        run: |
-          git clone --recursive https://code.qt.io/qt/qt5.git qt -b '${{env.QT_VERSION}}'
-          cd qt
-          perl init-repository.pl -f --module-subset=all,-qtopcua
-
-      - name: Set up MSVC
-        uses: ilammy/msvc-dev-cmd@v1
-        if: contains(matrix.os, 'windows')
-
-      - name: Build Qt (Windows)
-        if: contains(matrix.os, 'windows')
-        env:
-          CL: /MP # Build with multiple processes
-        run: |
-          mkdir qt_build                                         
-          cd qt_build                                           
-          ..\qt\configure.bat -prefix "..\qt_static" -release -static -static-runtime -optimize-size -opensource  -no-openssl -no-feature-accessibility
-          cmake --build . --parallel 4                         
-          cmake --install .                                     
-
-      - name: Build Qt (macOS)
-        if: contains(matrix.os, 'macos')
-        run: |
-          mkdir qt_build
-          cd qt_build
-          ../qt/configure -static -static-runtime -release -optimize-size -prefix "../qt_static" -no-feature-accessibility -- -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
-          cmake --build . --parallel 3
-          cmake --install .
-
-      - name: Package binaries
-        run: |
-          # 安装 zstd 和 tar
-          choco install zstd
-          choco install gnuwin32-tar 
-
-          # 使用 tar 打包并压缩为 .tar.zst
-          tar -cf - qt_static | zstd -o qt-${{env.QT_VERSION}}-static-${{matrix.os-caption}}.tar.zst
-
-      - uses: actions/upload-artifact@v4
+      - uses: actions/checkout@v4
         with:
-          name: qt-static-${{matrix.os-caption}}
-          path: qt-*.tar.zst
+          fetch-depth: 0
+      - uses: actions/download-artifact@v4
+        with:
+          path: release
+          merge-multiple: true
+      - uses: softprops/action-gh-release@v2
+        with:
+          files: release/*
 
+      - name: Shorthand tags
+        run: |
+          git config --global user.email "27856297+dependabot-preview[bot]@users.noreply.github.com"
+          git config --global user.name "github-actions[bot]"
+          git tag -d v$QT_VERSION || true
+          git tag v$QT_VERSION -m v$QT_VERSION
+          git push -f origin v$QT_VERSION
+          git tag -d v${QT_VERSION%.*} || true
+          git tag v${QT_VERSION%.*} -m v${QT_VERSION%.*}
+          git push -f origin v${QT_VERSION%.*}
